//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_TestSection
    {
        public Sys_TestSection()
        {
            this.Sys_StudentTestSection = new HashSet<Sys_StudentTestSection>();
            this.Sys_TestSectionAnswer = new HashSet<Sys_TestSectionAnswer>();
        }
    
        public string TestSection_ID { get; set; }
        public string Section_ID { get; set; }
        public string IsSetTime { get; set; }
        public string Test_Name { get; set; }
    
        public virtual Sys_Section Sys_Section { get; set; }
        public virtual ICollection<Sys_StudentTestSection> Sys_StudentTestSection { get; set; }
        public virtual ICollection<Sys_TestSectionAnswer> Sys_TestSectionAnswer { get; set; }
    }
}
