//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_TestLesson
    {
        public Sys_TestLesson()
        {
            this.Sys_StudentTest = new HashSet<Sys_StudentTest>();
            this.Sys_TestLessonAnswer = new HashSet<Sys_TestLessonAnswer>();
        }
    
        public string Test_ID { get; set; }
        public string Lesson_ID { get; set; }
        public string Test_Name { get; set; }
        public string IsSetTime { get; set; }
    
        public virtual ICollection<Sys_StudentTest> Sys_StudentTest { get; set; }
        public virtual ICollection<Sys_TestLessonAnswer> Sys_TestLessonAnswer { get; set; }
    }
}
