//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Course
    {
        public Sys_Course()
        {
            this.Sys_Assess = new HashSet<Sys_Assess>();
            this.Sys_CourseCategory = new HashSet<Sys_CourseCategory>();
            this.Sys_Section = new HashSet<Sys_Section>();
            this.Sys_StudentCourse = new HashSet<Sys_StudentCourse>();
            this.Sys_Target = new HashSet<Sys_Target>();
            this.Sys_TeacherCourse = new HashSet<Sys_TeacherCourse>();
        }
    
        public string Course_ID { get; set; }
        public string Course_Name { get; set; }
        public byte[] Avatar { get; set; }
        public string Video { get; set; }
        public string Description { get; set; }
        public Nullable<double> IsPrice { get; set; }
        public Nullable<double> IsPriceSale { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> IsOrder { get; set; }
    
        public virtual ICollection<Sys_Assess> Sys_Assess { get; set; }
        public virtual ICollection<Sys_CourseCategory> Sys_CourseCategory { get; set; }
        public virtual ICollection<Sys_Section> Sys_Section { get; set; }
        public virtual ICollection<Sys_StudentCourse> Sys_StudentCourse { get; set; }
        public virtual ICollection<Sys_Target> Sys_Target { get; set; }
        public virtual ICollection<Sys_TeacherCourse> Sys_TeacherCourse { get; set; }
    }
}
